/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stuff;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class emp_book extends javax.swing.JFrame {
    protected Connection conn=null;
    protected PreparedStatement ptst=null;
    protected ResultSet rs=null;
   
    public emp_book() {
        initComponents();
        clear_table();
        showBooks();
        autoDelete();
    }
    
    public ArrayList<Booking> bookList(){
        conn=main.connect(conn);
        ArrayList<Booking> bookList = new ArrayList<>();
        try{
            String ssql="select * from BOOKS";
            ptst=conn.prepareStatement(ssql);
            rs=ptst.executeQuery();
            Booking book;
            while(rs.next()){
                book=new Booking(rs.getInt("CODE"),rs.getString("LASTNAME"),rs.getString("FIRSTNAME"),rs.getString("REGION"),rs.getInt("ROOM_NO"),rs.getDate("CHECKIN"),rs.getDate("CHECKOUT"),rs.getInt("PRICE"));
                bookList.add(book);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return bookList;
    }
    protected void clear_table(){
        bookinfo.setModel(new DefaultTableModel(null,new String[]{"Κωδικος", "Επωνυμο", "Ονομα", "Περιοχη", "Δωματιο", "Check-in", "Check-out", "Χρεωση"}));  
    }
    
    public void showBooks(){
        ArrayList<Booking> book = bookList();
         DefaultTableModel model = (DefaultTableModel) bookinfo.getModel();
          Object[] row = new Object[8];
        for(int i=0;i<book.size();i++){
            row[0]=book.get(i).getCode();
            row[1]=book.get(i).getLastname();
            row[2]=book.get(i).getFirstname();
            row[3]=book.get(i).getRegion();
//            row[4]=book.get(i).getCategory();
            row[4]=book.get(i).getRoom_no();
            row[5]=book.get(i).getCheckin();
            row[6]=book.get(i).getCheckout();
            row[7]=book.get(i).getCharge();
            model.addRow(row);
        }
    }
    protected static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        return sDate;
    }
    protected void autoDelete(){
        //DIAGRAFI PROSFORWN POU EXOUNE LIKSEI
        java.util.Date today= new java.util.Date();
        java.sql.Date tDate = convertUtilToSql(today);
        try{
            String delete="select CHECKOUT from BOOKS";
            ptst=conn.prepareStatement(delete);
            rs=ptst.executeQuery();
            while(rs.next()){
                java.sql.Date Edate = rs.getDate("CHECKOUT");
                if(tDate.after(Edate)){
                    try{
                        String ndelete="delete from BOOKS where CHECKOUT=?";
                        ptst=conn.prepareStatement(ndelete);
                        ptst.setDate(1,Edate);
                        ptst.execute();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);  
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookinfo = new javax.swing.JTable();
        insertbook = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        deletebook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bookinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Κωδικος", "Επωνυμο", "Ονομα", "Περιοχη", "Δωματιο", "Check-in", "Check-out", "Χρεωση"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookinfo);

        insertbook.setText("Εισαγωγη Κρατησης");
        insertbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbookActionPerformed(evt);
            }
        });

        refresh.setText("Ανανεωση");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        deletebook.setText("Διαγραφη Κρατησης");
        deletebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(insertbook)
                        .addGap(66, 66, 66)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(deletebook)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertbook)
                    .addComponent(refresh)
                    .addComponent(deletebook))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebookActionPerformed
        //DIAGRAFI KRATISIS
        int delrow=bookinfo.getSelectedRow();
        if(delrow==-1){
            JOptionPane.showMessageDialog(null, "Παρακαλω διαλεξτε μια στηλη", "", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            int delcode=(int) bookinfo.getModel().getValueAt(delrow, 0);
            int choise=JOptionPane.showConfirmDialog(null, "Σιγουρα θελετε να διαγραψετε την κρατηση", "", JOptionPane.YES_NO_OPTION);
            if(choise==0){
                try{
                    String delsql="delete from BOOKS where CODE=?";
                    ptst=conn.prepareStatement(delsql);
                    ptst.setInt(1, delcode);
                    ptst.execute();
                    clear_table();
                    showBooks();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_deletebookActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        //REFRESH TON PINAKA
        clear_table();
        showBooks();
    }//GEN-LAST:event_refreshActionPerformed

    private void insertbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbookActionPerformed
        //EMFANISIS PARATHIROU PINAKA
        insert_book inbook = new insert_book();
        inbook.setSize(560,500);
        inbook.setLocationRelativeTo(null);
        inbook.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        inbook.setVisible(true);
    }//GEN-LAST:event_insertbookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookinfo;
    private javax.swing.JButton deletebook;
    private javax.swing.JButton insertbook;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
