/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stuff;
import java.awt.Color;
import java.awt.Component;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Chris
 */
public class room_status extends javax.swing.JFrame {
    protected Connection conn=null;
    protected PreparedStatement pst=null;
    protected ResultSet rs=null;
    /**
     * Creates new form room_status
     */
    public room_status() {
        initComponents();
        clear_table();  
        showAvail(); 
        
    }
    
    public ArrayList<Avail> availList(){
        conn=main.connect(conn);
        ArrayList<Avail> availList = new ArrayList<>();
        try{
            String ssql="select * from HOTEL";
            pst=conn.prepareStatement(ssql);
            rs=pst.executeQuery();
            Avail avail;
            while(rs.next()){
                avail=new Avail(rs.getInt("ROOM_NO"),rs.getString("CATEGORY"),rs.getString("REGION"),rs.getInt("PRICE"),rs.getBoolean("AVAILABLE"));
                availList.add(avail);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return availList;
    }
    protected void clear_table(){
        rstate.setModel(new DefaultTableModel(null,new String[]{"Κωδικος","Τυπος","Περιοχη","Τιμη","Διαθεσιμο"}));  
    }
    
    public void showAvail(){
        ArrayList<Avail> avail = availList();
         DefaultTableModel model = (DefaultTableModel) rstate.getModel();
          Object[] row = new Object[5];
        for(int i=0;i<avail.size();i++){
            row[0]=avail.get(i).getRoom_no();
            row[1]=avail.get(i).getType();
            row[2]=avail.get(i).getRegion();
            row[3]=avail.get(i).getPrice();
            row[4]=avail.get(i).isAvail();          
            model.addRow(row);
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rstate = new javax.swing.JTable();
        chstate = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        deleteroom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rstate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Δωματιο", "Τυπος", "Περιοχη", "Τιμη", "Διαθεσιμο"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rstate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rstateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rstate);

        chstate.setText("Αλλαγη Διαθεσιμοτητας Δωματιου");
        chstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chstateActionPerformed(evt);
            }
        });

        refresh.setText("Ανανεωση");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        exit.setText("Εξοδος");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        deleteroom.setText("Διαγραφη Δωματιου");
        deleteroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteroomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chstate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteroom)
                        .addGap(18, 18, 18)
                        .addComponent(refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chstate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteroom, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        //EKSODOS
        int choise=JOptionPane.showConfirmDialog(null, "Σιγουρα θελετε να κλεισετε το παραθυρο", "",JOptionPane.YES_NO_OPTION);
        if(choise==0){
            this.dispose();
            this.setVisible(false);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        //ANANEWSI PINAKA
        clear_table();
        showAvail();
    }//GEN-LAST:event_refreshActionPerformed

    private void chstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chstateActionPerformed
        // ENIMERWSI VASIS KAI UPDATE TO JTABLE
        int uproom=rstate.getSelectedRow();
        if(uproom==-1){
            JOptionPane.showMessageDialog(null, "Παρακαλω διαλεξτε μια εγγραφη", "", JOptionPane.ERROR_MESSAGE);
        }else{
            int upcode=(int) rstate.getModel().getValueAt(uproom, 0);
            boolean upstate=(boolean) rstate.getModel().getValueAt(uproom,4);
            try{
                if(upstate==true){
                    String upsql="update HOTEL set AVAILABLE=false where ROOM_NO=?";
                    pst=conn.prepareStatement(upsql);
                    pst.setInt(1, upcode);
                    pst.execute();
                }else{
                    String upsql="update HOTEL set AVAILABLE=true where ROOM_NO=?";
                    pst=conn.prepareStatement(upsql);
                    pst.setInt(1, upcode);
                    pst.execute();
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        clear_table();
        showAvail();
    }//GEN-LAST:event_chstateActionPerformed

    private void rstateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rstateMouseClicked
      
    }//GEN-LAST:event_rstateMouseClicked

    private void deleteroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteroomActionPerformed
        //DIAGRAGI DWMATIOU
        int delrow=rstate.getSelectedRow();
        if(delrow==-1){
            JOptionPane.showMessageDialog(null,"Παρακαλω διαλεξτε μια στηλη","",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            int delchoise=JOptionPane.showConfirmDialog(null, "Ειστε σιγουροι ?", "", JOptionPane.YES_NO_OPTION);
            if(delchoise==0){
                  int delroomno=(int)rstate.getValueAt(delrow, 0);
            String delreg=(String)rstate.getValueAt(delrow,2);
            try{
                String delsql="delete from HOTEL where ROOM_NO=? and REGION=?";
                pst=conn.prepareStatement(delsql);
                pst.setInt(1,delroomno);                
                pst.setString(2,delreg);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Επιτυχης διαγραφη δωματιου");
                clear_table();
                showAvail();
                
                }catch(Exception e){
                    e.printStackTrace();
                }  
            }       
        }
    }//GEN-LAST:event_deleteroomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room_status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chstate;
    private javax.swing.JButton deleteroom;
    private javax.swing.JButton exit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JTable rstate;
    // End of variables declaration//GEN-END:variables
}
