/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stuff;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Chris
 */
public class statistics extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement ptst=null;
    ResultSet rs=null;
    
    protected static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        return sDate;
    }
    
    public statistics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stdate = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        endate = new com.toedter.calendar.JCalendar();
        createGraphs = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        choise = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ημερομηνια Εναρξης");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ημερομηνια Ληξης");

        createGraphs.setText("Παραγωγη Γραφηματος");
        createGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGraphsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Περιοχη");

        choise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ολα τα ξενοδοχεια", "Αθηνα", "Θεσσαλονικη", "Ροδος", "Ηρακλειο", "Κεφαλονια" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(createGraphs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(choise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9))
                            .addComponent(endate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(choise, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdate, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(endate, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createGraphs, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGraphsActionPerformed
        //ELEGXOS IMEROMINIAS KAI PARAGWGI GRAFIMATWN
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        main mn = new main();
        conn=mn.connect(conn);
        int ch=choise.getSelectedIndex();
        Date stdt = convertUtilToSql(stdate.getDate());
        Date endt = convertUtilToSql(endate.getDate());
        if(endt.before(stdt)){
            JOptionPane.showMessageDialog(null, "Η τελικη ημερομηνια δεν μπορει να ειναι πριν την αρχικη", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        java.sql.Date rng = stdt;
        if(ch==0){
            while(rng.before(endt)){
                int cnt=0;
                try{
                    String selsql="select distinct * from  BOOKS where ? between CHECKIN and CHECKOUT";
                    ptst=conn.prepareStatement(selsql);
                    ptst.setDate(1, rng);
                    rs=ptst.executeQuery();
                    while(rs.next()){
                       cnt++; 
                    }
                    dataset.setValue(cnt,""," "+rng); 
                
                    //System.out.println(cnt);
                    rng.setDate(rng.getDate()+1);                              
                }catch(Exception e){
                    e.printStackTrace();
                }                 
            }
            JFreeChart chart = ChartFactory.createBarChart("ΓΡΑΦΙΚΗ","ΗΜΕΡΟΜΗΝΙΕΣ","ΚΡΑΤΗΣΕΙΣ",dataset,PlotOrientation.VERTICAL, false, true,false);
            CategoryPlot p = chart.getCategoryPlot();
            ChartFrame frame = new ChartFrame("TEST CHART",chart);
            frame.setVisible(true);
            frame.setSize(600, 600);
            frame.setLocationRelativeTo(null); 
        }else{
            String hchoise=(String)choise.getSelectedItem();
            while(rng.before(endt)){
                int cnt=0;
                try{
                    String selsql="select distinct * from  BOOKS where REGION=? and ? between CHECKIN and CHECKOUT";
                    ptst=conn.prepareStatement(selsql);
                    ptst.setString(1, hchoise);
                    ptst.setDate(2, rng);
                    rs=ptst.executeQuery();
                    while(rs.next()){
                       cnt++; 
                    }
                    dataset.setValue(cnt,""," "+rng); 
                
                    System.out.println(cnt);
                    rng.setDate(rng.getDate()+1);                              
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            JFreeChart chart = ChartFactory.createBarChart("ΓΡΑΦΙΚΗ","ΗΜΕΡΟΜΗΝΙΕΣ","ΚΡΑΤΗΣΕΙΣ",dataset,PlotOrientation.VERTICAL, false, true,false);
            CategoryPlot p = chart.getCategoryPlot();
            ChartFrame frame = new ChartFrame("TEST CHART",chart);
            frame.setVisible(true);
            frame.setSize(600, 600);
            frame.setLocationRelativeTo(null); 
        }   
    }//GEN-LAST:event_createGraphsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choise;
    private javax.swing.JButton createGraphs;
    private com.toedter.calendar.JCalendar endate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JCalendar stdate;
    // End of variables declaration//GEN-END:variables
}
