/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stuff;
//import stuff.*;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Chris
 */
public class view_offers extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement ptst=null;
    ResultSet rs=null;

    /**
     * Creates new form view_offers
     */
    public view_offers() {
        conn=main.connect(conn);
        initComponents();
        clear_table();
        showOffer();
        autoDelete();
    }
    protected static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        return sDate;
    }
    
    protected void autoDelete(){
        //DIAGRAFI PROSFORWN POU EXOUNE LIKSEI
        java.util.Date today= new java.util.Date();
        java.sql.Date tDate = convertUtilToSql(today);
        try{
            String delete="select FINISH from OFFERS";
            ptst=conn.prepareStatement(delete);
            rs=ptst.executeQuery();
            while(rs.next()){
                java.sql.Date Edate = rs.getDate("FINISH");
                if(tDate.after(Edate)){
                    try{
                        String ndelete="delete from OFFERS where FINISH=?";
                        ptst=conn.prepareStatement(ndelete);
                        ptst.setDate(1,Edate);
                        ptst.execute();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);  
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);  
        }
    }
    
    public ArrayList<Offer> offerList(){
        main mn = new main();
        conn=mn.connect(conn);
        ArrayList<Offer> offerList = new ArrayList<>();
        try{
            String sql="select distinct * from OFFERS";
            ptst=conn.prepareStatement(sql);
            rs=ptst.executeQuery();
            Offer offer;
            while(rs.next()){
                offer = new Offer(rs.getString("REGION"),rs.getString("TYPE"),rs.getDate("START"),rs.getDate("FINISH"),rs.getInt("PRICE"));
                offerList.add(offer);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"",JOptionPane.ERROR_MESSAGE);
        }
        return offerList;
    }
    public void showOffer(){
        ArrayList<Offer> offer = offerList();
        DefaultTableModel model = (DefaultTableModel) offertable.getModel();
        Object[] row = new Object[5];
        for(int i=0;i<offer.size();i++){
            row[0]=offer.get(i).getRegion();
            row[1]=offer.get(i).getType();
            row[2]=offer.get(i).getSdate();
            row[3]=offer.get(i).getEdate();
            row[4]=offer.get(i).getDiscount();
            model.addRow(row);
        }
    }
    
    
    
    protected void clear_table(){
        offertable.setModel(new DefaultTableModel(null,new String[]{"Περιοχη","Τυπος","Εναρξη","Ληξη","Εκπτωση"}));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        offertable = new javax.swing.JTable();
        insert = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        offertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Περιοχη", "Τυπος ", "Εναρξη ", "Ληξη", "Εκπτωση"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(offertable);

        insert.setText("Εισαγωγη Προσφορας");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        refresh.setText("Ανανεωση Πινακα");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        delete.setText("Διαγραφη Προσφορας");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insert)
                        .addGap(60, 60, 60)
                        .addComponent(refresh)
                        .addGap(60, 60, 60)
                        .addComponent(delete)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert)
                    .addComponent(refresh)
                    .addComponent(delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        //REFRESH PINAKA PORSOFWN
        clear_table();
        showOffer();
    }//GEN-LAST:event_refreshActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        //DIAGRAFI PROSFORAS APO TIN VASI
        main mn = new main();
        conn=mn.connect(conn);
        int delrow=offertable.getSelectedRow();
        if(delrow==-1){
            JOptionPane.showMessageDialog(null, "Παρακαλω διαλεξτε μια στηλη", "", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
           int confdel=JOptionPane.showConfirmDialog(null, "Σιγουρα θελετε να διαγραψετε την προσφορα ;", "", JOptionPane.YES_NO_OPTION);
           if(confdel==0){
                String delreg=(String)offertable.getModel().getValueAt(delrow, 0);
                String deltype=(String)offertable.getModel().getValueAt(delrow, 1);
                Date   delsdat=(Date) offertable.getModel().getValueAt(delrow, 2);
                Date   delfdat=(Date) offertable.getModel().getValueAt(delrow, 3);
                int    delpric=(int)  offertable.getModel().getValueAt(delrow, 4);
            try{
                String delsql="delete from OFFERS where REGION=? and TYPE=? and START=? and FINISH=? and PRICE=?";
                ptst=conn.prepareStatement(delsql);
                ptst.setString(1, delreg);
                ptst.setString(2, deltype);
                ptst.setDate(3, delsdat);
                ptst.setDate(4, delfdat);
                ptst.setInt(5, delpric);
                ptst.execute();
                clear_table();
                showOffer();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);
            }
           }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        //DIMIOURGIA PROSFORAS
        create_offer coffer = new create_offer();
        coffer.setSize(500,500);
        coffer.setLocationRelativeTo(null);
        coffer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        coffer.setVisible(true);
    }//GEN-LAST:event_insertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_offers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable offertable;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
