/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;
import stuff.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Chris
 */
public class booking extends javax.swing.JFrame {
    Connection bconn=conn=null;
    Connection conn=null;
    PreparedStatement ptst=null;
    ResultSet rs=null;
    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
        clear_table();
        showOffer();
        autoDelete();
    }
    protected static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        return sDate;
    }
    
    public ArrayList<Offer> offerList(){
        stuff.main mn = new main();
        conn=mn.connect(conn);
        ArrayList<Offer> offerList = new ArrayList<>();
        try{
            String sql="select distinct * from OFFERS";
            ptst=conn.prepareStatement(sql);
            rs=ptst.executeQuery();
            Offer offer;
            while(rs.next()){
                offer = new Offer(rs.getString("REGION"),rs.getString("TYPE"),rs.getDate("START"),rs.getDate("FINISH"),rs.getInt("PRICE"));
                offerList.add(offer);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"",JOptionPane.ERROR_MESSAGE);
        }
        return offerList;
    }
    public void showOffer(){
        ArrayList<Offer> offer = offerList();
        DefaultTableModel model = (DefaultTableModel) offertable.getModel();
        Object[] row = new Object[5];
        for(int i=0;i<offer.size();i++){
            row[0]=offer.get(i).getRegion();
            row[1]=offer.get(i).getType();
            row[2]=offer.get(i).getSdate();
            row[3]=offer.get(i).getEdate();
            row[4]=offer.get(i).getDiscount();
            model.addRow(row);
        }
    }
     protected void clear_table(){
        offertable.setModel(new DefaultTableModel(null,new String[]{"Περιοχη","Τυπος","Εναρξη","Ληξη","Εκπτωση"}));  
    }
    protected void autoDelete(){
        //DIAGRAFI PROSFORWN POU EXOUNE LIKSEI
        java.util.Date today= new java.util.Date();
        java.sql.Date tDate = convertUtilToSql(today);
        try{
            String delete="select FINISH from OFFERS";
            ptst=conn.prepareStatement(delete);
            rs=ptst.executeQuery();
            while(rs.next()){
                java.sql.Date Edate = rs.getDate("FINISH");
                if(tDate.after(Edate)){
                    try{
                        String ndelete="delete from OFFERS where FINISH=?";
                        ptst=conn.prepareStatement(ndelete);
                        ptst.setDate(1,Edate);
                        ptst.execute();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);  
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);  
        }
    } 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmbg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        region = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        chidate = new com.toedter.calendar.JCalendar();
        jLabel6 = new javax.swing.JLabel();
        chodate = new com.toedter.calendar.JCalendar();
        jLabel7 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        terms = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        offertable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        pmbg.add(cash);
        pmbg.add(card);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Επωνυμο");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ονομα");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Περιοχη");

        region.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Αθηνα", "Θεσσαλονικη", "Ροδος", "Ηρακλειο", "Κεφαλονια" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Κατηγορια");

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Μονοκλινο", "Δικλινο", "Τρικλινο", "Τετρακλινο", "Προεδρικη Σουιτα" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Check-in");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Check-out");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Τροπος Πληρωμης");

        cash.setText("Μετρητα");
        cash.setSelected(true);

        card.setText("Καρτα");

        submit.setEnabled(false);
        submit.setText("ΟΚ");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        clear.setText("Καθαρισμος");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        cancel.setText("Ακυρωση");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        terms.setText("Αποδεχομαι τους ορους χρησης");
        terms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                termsMouseClicked(evt);
            }
        });

        offertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Περιοχη", "Τυπος", "Εναρξη", "Ληξη", "Εκπτωση"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(offertable);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Προσφορες");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Εισαγωγη Κρατησης");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastname)
                            .addComponent(firstname)
                            .addComponent(region, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chidate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(chodate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(14, 14, 14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(50, 50, 50)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)
                                        .addComponent(card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(50, 50, 50)
                                .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(terms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(249, 249, 249)))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(region, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(category, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chidate, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(chodate, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                            .addComponent(cash))
                        .addGap(4, 4, 4))
                    .addComponent(card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(terms, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        //KATHARISMOS FORMAS
        lastname.setText("");
        firstname.setText("");
    }//GEN-LAST:event_clearActionPerformed
   
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        //AKIRWSI DIADIKASIAS
        int choise=JOptionPane.showConfirmDialog(null, "Σιγουρα θελετε να ακυρωσετε την διαδικασια","",JOptionPane.YES_NO_OPTION);
        if(choise==0){
            this.dispose();
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_cancelActionPerformed
    
    private void termsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_termsMouseClicked
        //ELEGXOS AN TO CHECKBOX EINAI PATIMENO
        if(terms.isSelected()){
            submit.setEnabled(true);
        }else{
            submit.setEnabled(false);
        }
    }//GEN-LAST:event_termsMouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        //ELEGXOS KAI EMFANISI PARATHIROU EPIVEVAIWSIS
        stuff.main mn = new main();
        conn=mn.connect(conn);
        
    
            book_conf bc = new book_conf();

            int kwdikos=(int)Math.round(Math.random() * 89999) + 10000;
            String code=Integer.toString(kwdikos);
            bc.code.setText(code);

            bc.lastname.setText(this.lastname.getText());
            bc.firstname.setText(this.firstname.getText());

            String reg=(String) region.getSelectedItem();
            String cat=(String) category.getSelectedItem();

            bc.region.setText(reg);
            bc.category.setText(cat);

            java.sql.Date sdate=convertUtilToSql(chidate.getDate());
            java.sql.Date edate=convertUtilToSql(chodate.getDate());

            String fdate=sdate.toString();
            String tdate=edate.toString();

            bc.chin.setText(fdate);
            bc.chout.setText(tdate);

            try{
                String ofsql="select * from OFFERS where REGION=? and TYPE=? and ? between START and FINISH";
                ptst=conn.prepareStatement(ofsql);
                ptst.setString(1, reg);
                ptst.setString(2, cat);
                ptst.setDate(3, sdate);
                rs=ptst.executeQuery();
                if(rs.next()){
                    long price=rs.getInt("PRICE")*((edate.getTime()-sdate.getTime())/(1000*60*60*24));
                            String charg=Long.toString(price);
                            bc.charge.setText(charg);    
                }else{
                    String hotpr="select PRICE from HOTEL where REGION=? and CATEGORY=?";
                    ptst=conn.prepareStatement(hotpr);
                    ptst.setString(1, reg);
                    ptst.setString(2, cat);
                    rs=ptst.executeQuery();
                    if(rs.next()){
                        long hprice=rs.getInt("PRICE")*((edate.getTime()-sdate.getTime())/(1000*60*60*24));
                        String chrg=Long.toString(hprice);
                        bc.charge.setText(chrg);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e,"", JOptionPane.ERROR_MESSAGE);
            }

            try{
                String chbook="select * from BOOKS where REGION=? and CATEGORY=?";
                ptst=conn.prepareStatement(chbook);
                ptst.setString(1, reg);
                ptst.setString(2, cat);
                rs=ptst.executeQuery();
                if(rs.next()){
                    try{
                        String sql="SELECT * FROM HOTEL WHERE   HOTEL.REGION=? and HOTEL.CATEGORY=? and AVAILABLE=true and HOTEL.ROOM_NO NOT IN(SELECT ROOM_NO FROM BOOKS WHERE ? BETWEEN CHECKIN AND CHECKOUT OR ? BETWEEN CHECKIN AND CHECKOUT)";
                        ptst=conn.prepareStatement(sql);
                        ptst.setString(1,reg);
                        ptst.setString(2,cat);
                        ptst.setDate(3,sdate);
                        ptst.setDate(4,edate);
                        rs=ptst.executeQuery();
                        if(rs.next()){
                          int irn=rs.getInt("ROOM_NO");                      
                         bc.hotbooknum=irn;
                        }else{
                            JOptionPane.showMessageDialog(null, "Δεν υπαρχουν διαθεσιμα δωματια","", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                     }catch(Exception e){
                            JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    bc.chin.setText(fdate);
                    bc.chout.setText(tdate);
                    kwdikos=(int)Math.round(Math.random() * 89999) + 10000;
                    code=Integer.toString(kwdikos);
                    bc.code.setText(code);

                    bc.lastname.setText(this.lastname.getText());
                    bc.firstname.setText(this.firstname.getText());

                    reg=(String) region.getSelectedItem();
                    cat=(String) category.getSelectedItem();

                    bc.region.setText(reg);
                    bc.category.setText(cat);

                    sdate=convertUtilToSql(chidate.getDate());
                    edate=convertUtilToSql(chodate.getDate());

                    fdate=sdate.toString();
                    tdate=edate.toString();
                     try{
                         String sql="SELECT * FROM HOTEL WHERE   HOTEL.REGION=? and HOTEL.CATEGORY=? and AVAILABLE=true ";
                         ptst=conn.prepareStatement(sql);
                         ptst.setString(1, reg);
                         ptst.setString(2, cat);
                         rs=ptst.executeQuery();                   
                        if(rs.next()){
                          int irn=rs.getInt("ROOM_NO");
                          bc.hotbooknum=irn;
                        }else{
                            JOptionPane.showMessageDialog(null, "Δεν υπαρχουν διαθεσιμα δωματια","", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                     }catch(Exception e){
                          JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);
                     }
                }
            }catch(Exception e){
                e.printStackTrace();
            }

            bc.setSize(350, 520);
            bc.setLocationRelativeTo(null);
            bc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bc.setVisible(true);    
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JRadioButton card;
    private javax.swing.JRadioButton cash;
    private javax.swing.JComboBox<String> category;
    private com.toedter.calendar.JCalendar chidate;
    private com.toedter.calendar.JCalendar chodate;
    private javax.swing.JButton clear;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTable offertable;
    private javax.swing.ButtonGroup pmbg;
    private javax.swing.JComboBox<String> region;
    private javax.swing.JButton submit;
    private javax.swing.JCheckBox terms;
    // End of variables declaration//GEN-END:variables
}
